### PR TITLE
Minor Refactoring in branch m2-demo-on-cluster's README

### PR DESCRIPTION
**Pull request by scoheb**

### CODE REVIEW

**Review by samyak-jn — APPROVED** [review]
Good catch!

**Comment by samyak-jn** [comment]
Hi @scoheb, :wave: 

Can you add the commit from PR #66 here only, if that's possible? :smile: 
Also, let's keep this PR open until skim through all the steps one from the readme to add/refractor more if needed.

**Comment by scoheb** [comment]
updated!

**Comment by jgwest** [comment]
Good catch, thanks @scoheb  and @samyak-jn!

**Pull request merged**
