### PR TITLE
Bump argocd to v2.5.1

### PR DESCRIPTION
**Pull request by drpaneas**
#### Description:
- Bumps ArgoCD v2.5.1

#### Link to JIRA Story (if applicable):

https://issues.redhat.com/browse/GITOPSRVCE-198

### CODE REVIEW

**Review by samyak-jn — COMMENTED** [review]
/lgtm, though mocks added a lot of LOCs, I checked for the docs to reflect the correct version, and minor changes are done in dial time and pointer assignment. Plus taking CI as a source of truth :green_circle: 

Thanks @drpaneas :beers:

**Review by jgwest — APPROVED** [review]
LGTM too @drpaneas , thanks for getting into the weeds on Argo CD/K8s go.mod package dependencies :laughing:!

**Pull request merged**
