### PR TITLE
GITOPSRVCE-179: Move 'redhat-appstudio/gitops-repository-template'

### PR DESCRIPTION
**Pull request by akram**
#### Description:
Move 'redhat-appstudio/gitops-repository-template' content to this repository and update references

#### Link to JIRA Story (if applicable):

[GITOPSRVCE-179](https://issues.redhat.com/browse/GITOPSRVCE-179)

### CODE REVIEW

**Comment by samyak-jn** [comment]
Thanks for the PR @akram :taco: 
Have triggered the workflow now to run all the tests in CI

**Comment by jgwest** [comment]
@akram, my guess is that this will pass once it's actually running in production (e.g. it's due to the issue described on Slack), so it will get merged shortly, but I want to wait for the remaining PRs from the previous sprint to merge first (in case we DO break things with this PR :smile: )

**Comment by akram** [comment]
ok @jgwest , safety first :-)

**Review by jgwest — APPROVED** [review]
Looks perfect, thank @akram! I tested this on my local branch and it worked great. Thanks for your patience in waiting to getting this in :sweat_smile:

**Pull request merged**
