### PR TITLE
Refactor repocred tests to use operations.CreateOperation()

### PR DESCRIPTION
**Pull request by drpaneas**
#### Description:
- Changing from `dbq.CreateOperation()` into `operations.CreateOperation()`. The first one creates only the DB Row, while the second one it goes on step further and creates also the corresponding CR in the cluster.

#### Link to JIRA Story (if applicable):

REF: https://issues.redhat.com/browse/GITOPSRVCE-96

### CODE REVIEW

**Review by chetan-rns — APPROVED** [review]
Thanks @drpaneas 
/lgtm

**Review by samyak-jn — APPROVED** [review]
/lgtm as well.
Should we consider opening a "task" in JIRA for the ToDo mentioned in the PR?

**Comment by drpaneas** [comment]
> /lgtm as well. Should we consider opening a "task" in JIRA for the ToDo mentioned in the PR?

what ToDo?

**Review by jgwest — APPROVED** [review]
LGTM as well, thanks @drpaneas!

**Pull request merged**
