### PR TITLE
Disable appstudio logic which create a GitOpsDeployment for every AppStudio Application

### PR DESCRIPTION
**Pull request by Rizwana777**
#### Description:
- Moved code logic of creating GitopsDeployment from Reconcile function of application_controller.go to a new function called gitopsDeploymentCreation
-  gitopsDeploymentCreation  function is not called anywhere
- Added `nolint` comment to avoid lint error

#### Link to JIRA Story (if applicable):

https://issues.redhat.com/browse/GITOPSRVCE-215

### CODE REVIEW

**Review by drpaneas — APPROVED** [review]
/lgtm - let's wait until the e2e are fixed to retest this, just to be on the safe side. Other than that, looks good to go.

**Comment by Rizwana777** [comment]
> /lgtm - let's wait until the e2e are fixed to retest this, just to be on the safe side. Other than that, looks good to go.

okay Panos, thank you !

**Review by jgwest — APPROVED** [review]
LGTM, thanks @Rizwana777!

**Pull request merged**
