### PR TITLE
fix intermittent E2E test failure in 'argocd_instance_test.go'

### PR DESCRIPTION
**Pull request by chetan-rns**
#### Description:
- Retry if there is a conflict while updating the service account

#### Link to JIRA Story (if applicable):

https://issues.redhat.com/browse/GITOPSRVCE-782

### CODE REVIEW

**Comment by Rizwana777** [comment]
tests are passing

**Review by jgwest — APPROVED** [review]
LGTM, thanks @chetan-rns, and thanks @Rizwana777 for reviewing!

**Pull request merged**
