### PR TITLE
Update ServiceAccount client to use client.Client, refactor ServiceAccount creation logic, tests

### PR DESCRIPTION
**Pull request by jgwest**
#### Description:
- Update ServiceAccount client to use client.Client, rather than a clientset
- Refactor ServiceAccount creation logic, switch to cluser-scoped clusterrole/rolebinding
- Tweak tests, switch to Ginkgo v2

### CODE REVIEW

**Review by samyak-jn — COMMENTED** [review]
The interesting part to see, the unit tests from openshift-ci are passing, whereas from GitHub Actions are failing :exploding_head:

**Comment by jgwest** [comment]
@samyak-jn Makes sense in this case, actually, because the tests requires a K8s cluster: which openshift CI has and github actions doesn't. I broke the Skip() call, whose job was to skip the test if there isn't a k8s cluster present.

**Comment by jgwest** [comment]
No review comments after a week, and the changes are uncontroversial, so merging.

**Pull request merged**
