### PR TITLE
Fix e2e tests which are failing

### PR DESCRIPTION
**Pull request by Rizwana777**
#### Description:
- Fixed e2e tests which are failing

### CODE REVIEW

**Comment by drpaneas** [comment]
@Rizwana777 great work. I've tested it locally and indeed this fixes the issue.

**Comment by Rizwana777** [comment]
> @Rizwana777 great work. I've tested it locally and indeed this fixes the issue.

Thanks Panos, CI got passed for e2e tests, PTAL

**Review by drpaneas — APPROVED** [review]
/lgrm

**Comment by drpaneas** [comment]
I've tested this 5 times locally and the e2e are now passing fine.
The CI here at GitHub also run twice and the E2E were green.
Rizwana also tested this locally as well.

I need this (and I guess the rest of the team) asap. Any objections to merge it?

**Comment by drpaneas** [comment]
Nice fixtured for the labels @jgwest  let me test those as well ;)

**Comment by drpaneas** [comment]
it works for me locally as well
/lgtm

**Review by jgwest — APPROVED** [review]
LGTM, thanks @Rizwana777, I added another commit which combines our changes together, and thanks @drpaneas for trying it out

**Pull request merged**
