### PR TITLE
Fix PromotionRun E2E test.

### PR DESCRIPTION
**Pull request by jparsai**
#### Description:
This PR is to fix an issue with one of the PromotionRun E2E tests.

#### Jira Ticket:
https://issues.redhat.com/browse/GITOPSRVCE-234

### CODE REVIEW

**Review by samyak-jn — COMMENTED** [review]
Hi @jparsai 

Please remove this check as well to test this e2e test in kcp as well

```
if fixture.IsRunningAgainstKCP() {
      Skip("Skipping this test in KCP until we fix the race condition")
}
```

**Comment by jparsai** [comment]
Yes @samyak-jn, I will remove that as well. I was thinking of testing it first on OpenShift CI with few PRs, if it fails again it will block KCP as well.

**Comment by jparsai** [comment]
E2E failed in last run but looks like it was caused by timeout not PromotionRun test.
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_managed-gitops/233/pull-ci-redhat-appstudio-managed-gitops-main-managed-gitops-e2e-tests/1575493113122656256

**Comment by jparsai** [comment]
Failed again due to timeout error https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_managed-gitops/233/pull-ci-redhat-appstudio-managed-gitops-main-managed-gitops-e2e-tests/1576801461721894912

**Comment by jparsai** [comment]
Error :- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_managed-gitops/233/pull-ci-redhat-appstudio-managed-gitops-main-managed-gitops-e2e-tests/1577273167800438784

**Review by samyak-jn — APPROVED** [review]
/lgtm, :green_circle:

**Review by jgwest — APPROVED** [review]
LGTM too, thanks @jparsai!

**Pull request merged**
