### PR TITLE
Exclude *.kcp.dev resources from Argo CD watch list

### PR DESCRIPTION
**Pull request by chetan-rns**
#### Description:
- Add resource exclusions to Argo CD CR and argocd-cm config map
- Update syncer image to v0.9.1 and fix the script

#### Link to JIRA Story (if applicable):
https://issues.redhat.com/browse/GITOPSRVCE-242

### CODE REVIEW

**Comment by chetan-rns** [comment]
@jgwest I've fixed the e2e tests. PTAL

**Review by jgwest — APPROVED** [review]
LGTM, thanks @chetan-rns!

**Pull request merged**
