### PR TITLE
Replace appstudio-shared imports to application-api

### PR DESCRIPTION
**Pull request by drpaneas**
#### Description:
- All the "imports" in our monorepo are now using the `https://github.com/redhat-appstudio/application-api/tree/main/api/v1alpha1`
- Update `go.mod`

#### Link to JIRA Story (if applicable):

https://issues.redhat.com/browse/GITOPSRVCE-236

### CODE REVIEW

**Review by jgwest — CHANGES_REQUESTED** [review]
Looks perfect, thanks @drpaneas! Just a comments re: `Makefile` then good to go.

**Comment by drpaneas** [comment]
@jgwest thanks for the feedback. I've addressed your points for the Makefile. Should be ready to merge now.

**Review by jgwest — APPROVED** [review]
LGTM, thanks again @drpaneas!

**Pull request merged**
