### PR TITLE
GitOpsDeploymentManagedEnvironment connection issue with cluster having self-signed certificate.

### PR DESCRIPTION
**Pull request by jparsai**
## Description:
This PR is to fix the bug when GitOpsDeploymentManagedEnvironment does not connect to cluster with self-signed certificate.

## JIRA Ticket:
https://issues.redhat.com/browse/RHTAPBUGS-520

### CODE REVIEW

**Comment by jgwest** [comment]
@jparsai 

I'm seeing this error in the E2E test logs, under `artifacts/managed-gitops-e2e-tests/gather-extra/artifacts/pods/gitops_gitops-core-service-controller-manager-58bfb4bf96-lrvbd_manager.log`

```json
{
  "level": "error",
  "ts": "2023-08-01T14:06:42.648402457Z",
  "logger": "managed-gitops",
  "caller": "application_event_loop/application_event_runner.go:181",
  "msg": "error from inner event handler in applicationEventLoopRunner",
  "namespaceID": "ef1a434f-5a5c-4178-a0fc-ef1574aa818e",
  "debugContext": "deployment",
  "event": "[DeploymentModified] gitops-service-e2e/my-gitops-depl/GitOpsDeployment, for workspace 'ef1a434f-5a5c-4178-a0fc-ef1574aa818e'",
  "error": "unable to get or create managed environment, isworkspacetarget:false: unable to get or create managed environment when reconciling for GitOpsDeployment: unable to create managed environment for 0b6e90c9-47ce-4c53-9ab0-349838d88b7d: unable to create new cluster credentials for managed env, while creating new managed env: unable to create k8s client from restConfig from managed environment secret: specifying a root certificates file with the insecure flag is not allowed",
  "stacktrace": "github.com/redhat-appstudio/managed-gitops/backend/eventloop/application_event_loop.applicationEventLoopRunner\n /workspace/backend/eventloop/application_event_loop/application_event_runner.go:181\ngithub.com/redhat-appstudio/managed-gitops/backend/eventloop/application_event_loop.startNewApplicationEventLoopRunner.func1\n /workspace/backend/eventloop/application_event_loop/application_event_runner.go:71"
}
```
Is this something that needs to be updated in the code?

**Comment by jparsai** [comment]
> @jparsai
> 
> I'm seeing this error in the E2E test logs, under `artifacts/managed-gitops-e2e-tests/gather-extra/artifacts/pods/gitops_gitops-core-service-controller-manager-58bfb4bf96-lrvbd_manager.log`
> 
> ```json
> {
>   "level": "error",
>   "ts": "2023-08-01T14:06:42.648402457Z",
>   "logger": "managed-gitops",
>   "caller": "application_event_loop/application_event_runner.go:181",
>   "msg": "error from inner event handler in applicationEventLoopRunner",
>   "namespaceID": "ef1a434f-5a5c-4178-a0fc-ef1574aa818e",
>   "debugContext": "deployment",
>   "event": "[DeploymentModified] gitops-service-e2e/my-gitops-depl/GitOpsDeployment, for workspace 'ef1a434f-5a5c-4178-a0fc-ef1574aa818e'",
>   "error": "unable to get or create managed environment, isworkspacetarget:false: unable to get or create managed environment when reconciling for GitOpsDeployment: unable to create managed environment for 0b6e90c9-47ce-4c53-9ab0-349838d88b7d: unable to create new cluster credentials for managed env, while creating new managed env: unable to create k8s client from restConfig from managed environment secret: specifying a root certificates file with the insecure flag is not allowed",
>   "stacktrace": "github.com/redhat-appstudio/managed-gitops/backend/eventloop/application_event_loop.applicationEventLoopRunner\n /workspace/backend/eventloop/application_event_loop/application_event_runner.go:181\ngithub.com/redhat-appstudio/managed-gitops/backend/eventloop/application_event_loop.startNewApplicationEventLoopRunner.func1\n /workspace/backend/eventloop/application_event_loop/application_event_runner.go:71"
> }
> ```
> 
> Is this something that needs to be updated in the code?

Yes @jgwest I am trying to fix it, I am unable to reproduce it in local system so I can only analyze CI logs to guess the problem.
looks like this is the root cause 
`unable to create k8s client from restConfig from managed environment secret: specifying a root certificates file with the insecure flag is not allowed`

**Comment by jgwest** [comment]
Hey @jparsai,

I pushed a commit which seems like it is getting past the issue you were seeing. 

To find out how to get past it, I did:
```bash
cd backend
go mod vendor

# Find where the error message is coming from in the dependencies
grep -r -i "specifying a root certificates file with the insecure flag is not allowed"
utilities/init-container/vendor/k8s.io/client-go/transport/transport.go:		return nil, fmt.Errorf("specifying a root certificates file with the insecure flag is not allowed"
```
Which let me know that the message was coming from client-go, and then I opened that module via `code utilities/init-container/vendor/k8s.io/client-go/transport/transport.go` and searched for that error message, to find the particular fields that we need to remove/ignore in this case. 

This seems like a reasonable solution to me, but if you can see any issues with us doing this, let's discuss it further.

**Review by jgwest — APPROVED** [review]
Looks great, thanks @jparsai!

**Pull request merged**
