### PR TITLE
GitOps Service should require TLS for postgresql

### PR DESCRIPTION
**Pull request by jopit**
#### Description:
- Update database connection code to require tls unless the DEV_ONLY_ALLOW_NON_TLS_CONNECTION_TO_POSTGRESQL environment variable is set.

### CODE REVIEW

**Review by chetan-rns — APPROVED** [review]
Looks good. Thanks @jopit. 

/lgtm

**Comment by chetan-rns** [comment]
Is there an easy way to test this locally without RDS?

**Comment by jgwest** [comment]
Rebase to latest

**Review by jgwest — APPROVED** [review]
LGTM, thanks @jopit and thanks @chetan-rns for reviewing!

**Pull request merged**
