### PR TITLE
Remove KCP Go dependencies

### PR DESCRIPTION
**Pull request by Rizwana777**
#### Description:
- Removed KCP GO dependencies
- As per the documentation of Ginkgo the `slowSpecThreshold` which we are using in our tests to check whether our tests are slow has been deprecated in version 2.5.0 `{KeyPath: “D.SlowSpecThreshold”, DeprecatedName: “slow-spec-threshold”, SectionKey: “output”, Usage: “--slow-spec-threshold has been deprecated and will be removed in a future version of Ginkgo.  This feature has proved to be more noisy than useful.  You can use --poll-progress-after, instead, to get more actionable feedback about potentially slow specs and understand where they might be getting stuck.“, DeprecatedVersion: “2.5.0”}` , I have made some changes to suite tests files as mentioned above where I have use pollProgressAfter

#### Link to JIRA Story (if applicable):
https://issues.redhat.com/browse/GITOPSRVCE-510

### CODE REVIEW

**Review by chetan-rns — COMMENTED** [review]
Looks good @Rizwana777. I still see some references to KCP in the codebase. Can you please update them?

I've listed some of them below. You can verify by searching the keyword `kcp` in your editor/IDE

1. `VwsAPIExpoerName` field can be removed in the [ApplicationEventQueueLoop](https://github.com/redhat-appstudio/managed-gitops/blob/57c1cf1714b1328948d5b2b9b86dbabdd46f1fba/backend/eventloop/application_event_loop/application_event_loop.go#L82) struct.
2. Update the comment for [GetK8sClientForGitOpsEngineInstance](https://github.com/redhat-appstudio/managed-gitops/blob/57c1cf1714b1328948d5b2b9b86dbabdd46f1fba/backend/eventloop/eventlooptypes/types.go#L137-L138)
3. Remove TODO comments to story GITOPSRVCE-19
4. Remove KCP references from [create-dev-env.sh](https://github.com/redhat-appstudio/managed-gitops/blob/57c1cf1714b1328948d5b2b9b86dbabdd46f1fba/create-dev-env.sh#L149)

**Review by jgwest — APPROVED** [review]
Looks great, thanks @Rizwana777! And thanks @chetan-rns for reviewing

**Pull request merged**
