### PR TITLE
Move Appstudio Environment E2E tests from core folder to appstudio folder

### PR DESCRIPTION
**Pull request by jgwest**
#### Description:
[tests-e2e/core/environment_test.go → tests-e2e/appstudio/environment_test.go](https://github.com/redhat-appstudio/managed-gitops/compare/main...jgwest:managed-gitops:move-environment-e2e-test-may-2023?expand=1#diff-169b9874a213bf183b0dac8ad1e77ff10c6a8957ccf87ec80c83c4992eef5e02)

### CODE REVIEW

**Comment by Rizwana777** [comment]
/lgtm , e2e test were failing for known issue in this PR,  
 ```
[FAILED] Expected
      <string>: test-dt-fake
  to equal
      <string>: test-dt
```

**Comment by jgwest** [comment]
Thanks @Rizwana777!

**Pull request merged**
