### PR TITLE
Chore: Get dev env working on cluster-bot hypershift (#417)

### PR DESCRIPTION
**Pull request by keithchong**
#### Description:
(Provide a brief list of the changes you have made, and why you made those changes, if it is not obvious why)

- I removed/disabled installing the default instance of Argo CD and adjusted the script to not wait for it to complete.
- We don't seem to need it, and we have a copy of the subscription anyway
- After doing this, and configuring the test environment, the tests all ran fine.
  
- (You don't need to mention any changes/reasons which are already documented in the JIRA story)
- See Jira

#### Link to JIRA Story (if applicable):

Fixes https://issues.redhat.com/browse/GITOPSRVCE-417

### CODE REVIEW

**Comment by keithchong** [comment]
I'm seeing the error reported by the e2e tests when I now run setup.  Will have to investigate this.

**Comment by keithchong** [comment]
The e2e tests passed.

**Review by jgwest — APPROVED** [review]
LGTM, thanks @keithchong! I look forward to using this :smile:

**Pull request merged**
