### PR TITLE
chore: improve test coverage.

### PR DESCRIPTION
**Pull request by jparsai**
#### Description:
This PR is to cover deleteArgoCDApplicationOfDeletedApplicationRow function, of Cluster-agent component.

#### JIRA Ticket:
https://issues.redhat.com/browse/GITOPSRVCE-703

### CODE REVIEW

**Comment by Rizwana777** [comment]
@jparsai I think we can cover log errors as well in deleteArgoCDApplicationOfDeletedApplicationRow function by creating mocks similar to this https://github.com/redhat-appstudio/managed-gitops/pull/612 ?

**Comment by jparsai** [comment]
> @jparsai I think we can cover log errors as well in deleteArgoCDApplicationOfDeletedApplicationRow function by creating mocks similar to this #612 ?

That is a good suggestion @Rizwana777, but unfortunately there will be a lot of effort required, 
for example here https://github.com/redhat-appstudio/managed-gitops/blob/main/cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop.go#L967
log message will be printed only if I get an error, but there is no way I can cause labels.NewRequirement() to fail without mocking this function as well. If I go with mocking function then it has to be done for many other functions as well.

**Comment by Rizwana777** [comment]
> > @jparsai I think we can cover log errors as well in deleteArgoCDApplicationOfDeletedApplicationRow function by creating mocks similar to this #612 ?
> 
> That is a good suggestion @Rizwana777, but unfortunately there will be a lot of effort required, for example here https://github.com/redhat-appstudio/managed-gitops/blob/main/cluster-agent/controllers/managed-gitops/eventloop/operation_event_loop.go#L967 log message will be printed only if I get an error, but there is no way I can cause labels.NewRequirement() to fail without mocking this function as well. If I go with mocking function then it has to be done for many other functions as well.

I agree @jparsai thank you

**Review by jgwest — CHANGES_REQUESTED** [review]
Looks great, one final request: can we also verify that the `AppProject` is deleted, and/or not deleted (exists), for the test cases? (more info on cluster agent appproject behaviour is [here](https://github.com/redhat-appstudio/managed-gitops/blob/main/docs/sandboxing-via-appprojects.md#changes-to-cluster-agent-component) if useful).

**Comment by jparsai** [comment]
> Looks great, one final request: can we also verify that the `AppProject` is deleted, and/or not deleted (exists), for the test cases? (more info on cluster agent appproject behaviour is [here](https://github.com/redhat-appstudio/managed-gitops/blob/main/docs/sandboxing-via-appprojects.md#changes-to-cluster-agent-component) if useful).

It is done, PTAL.

**Comment by jparsai** [comment]
/test managed-gitops-e2e-tests

Failing in `operation_namespace_test.go`, which has no changes in this PR, hence triggering once again.

**Review by jgwest — APPROVED** [review]
LGTM, thanks @jparsai!

**Pull request merged**
