### PR TITLE
Sync main and service-first branch using Github Action

### PR DESCRIPTION
**Pull request by saumeya**
#### Description:

For the nightly build of the service, we are using the service-first branch to solve the issue with local dependency.
This github action will sync the 'main' and 'service-first' branch by creating auto PRs whenever a new push is made to the main branch

#### Link to JIRA Story (if applicable):

https://issues.redhat.com/browse/GITOPSRVCE-274

### CODE REVIEW

**Comment by drpaneas** [comment]
Add `workflow_dispatch` in case we want to manually trigger this.

**Comment by saumeya** [comment]
> What's the empty-commit for?

I wanted to re-run the CI tests as they were failing

**Comment by saumeya** [comment]
@jgwest @drpaneas could you merge?

**Review by drpaneas — APPROVED** [review]
/lgtm

**Comment by drpaneas** [comment]
> @jgwest @drpaneas could you approve and merge (after e2e passes)?

I approved it but I am a mere mortal on this repository. You need power that only the Gods have.

**Review by jgwest — APPROVED** [review]

**Pull request merged**
