### PR TITLE
Update the GitOpsDeployment CR status field based on corresponding ApplicationState database entries

### PR DESCRIPTION
**Pull request by drpaneas**
This PR adds two new fields in the `.status` of the `GitOpsDeployment CR` coming from the original Argo CD Application CR:

* Revision: https://github.com/argoproj/argo-cd/blob/5676ab5c9bc37cf4d8e60968745f30a3eeb98038/pkg/apis/application/v1alpha1/types.go#L1040
* Message: https://github.com/argoproj/gitops-engine/blob/e360551b19d58b133fb3e98ce420bd696b76176c/pkg/health/health.go#L37

To do that, the following steps were taken:

1. Add the fields to `db-schema.sql`. Both of them are `omitempty` so there is _no_ need to add `NOT NULL`. The char magic number I've used is `1024`.
2. Add the fields to [backend-shared/config/db/types.go](https://github.com/redhat-appstudio/managed-gitops/blob/main/backend-shared/config/db/types.go#L224) into the `ApplicationState` struct, followed by their `pg` name.

Reload the database in k8s and debug the backend-controller. You notice that the `applicationState := db.ApplicationState{Applicationstate_application_id: mapping.Application_id}` will return the new fields:

3. Update the local `gitopsDeployment` instance by retrieving the relevant status fields from the `applicationState`:

```go
gitopsDeployment.Status.Health.Status = managedgitopsv1alpha1.HealthStatusCode(applicationState.Health)
gitopsDeployment.Status.Health.Message = applicationState.Message
gitopsDeployment.Status.Sync.Status = managedgitopsv1alpha1.SyncStatusCode(applicationState.Sync_Status)
gitopsDeployment.Status.Sync.Revision = applicationState.Revision
```

4. Push the `gitopsDeployment` local instance to k8s via the `workspaceClient.Status().Update`.

I can now manually modify the application CR: `kubectl -n argocd edit application gitopsdepl-ddf63aa5-2d96-4302-bcf2-8d0efbbb81ac -o yaml`

**Application CR**

```yaml=
status:
  health:
    status: Progressing <--- I added this manually
  summary: {}
```

And this is now depicted in the `GitOpsDeployment` CR as well: `kubectl -n default get gitopsdeployment gitopsdeployment-sample -o yaml`

**GitopsDeployment CR**

```yaml=
status:
  health:
    status: Progressing <---- it's updated as well
  sync:
    status: Unknown <---
```

5. Update the `Message` and `Revision` as well, by modifying the _application_controller_ of the cluster-agent:
See: https://github.com/redhat-appstudio/managed-gitops/blob/main/cluster-agent/controllers/argoproj.io/application_controller.go#L104
See: https://github.com/redhat-appstudio/managed-gitops/blob/main/cluster-agent/controllers/argoproj.io/application_controller.go#L130

To test this, modify again the Application CR: `kubectl -n argocd edit application gitopsdepl-f4460a37-0573-4af4-a8f0-e6151978723a`

**ArgoCD Application CR**

```yaml=
status:
  health:
    message: Hello, this is a message from health <-- add this manually
    status: Progressing <-- add this manually
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    revision: This is a revision msg <-- Add this manually
```

The ApplicationState is getting update, as you can see here:

And also does the Deployment CR as well: `$ kubectl -n default get gitopsdeployment gitopsdeployment-sample -o yaml`

**GitOps Deployment CR**

```yaml=
apiVersion: managed-gitops.redhat.com/v1alpha1
kind: GitOpsDeployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"managed-gitops.redhat.com/v1alpha1","kind":"GitOpsDeployment","metadata":{"annotations":{},"name":"gitopsdeployment-sample","namespace":"default"},"spec":{"source":{"repoURL":"https://github.com/drpaneas/whatever"},"type":"manual"}}
  creationTimestamp: "2022-02-14T14:06:37Z"
  generation: 1
  name: gitopsdeployment-sample
  namespace: default
  resourceVersion: "1228"
  uid: f4460a37-0573-4af4-a8f0-e6151978723a
spec:
  source:
    repoURL: https://github.com/drpaneas/whatever
  type: manual
status:
  health:
    message: Hello, this is a message from health <---
    status: Progressing <---
  sync:
    revision: This is a revision msg <----
    status: Unknown <---
```

Please let me know if this logic is correct :)

---

FYI: Originally I forgot to drop the `NOT NULL` in the db, so I've got two errors:
* Backend Controller Error: `ApplicationState row '2e01e4d8-cef0-4d33-b6a4-7b1f146c6360': no rows in result set`
* Cluster-Agent Controller Error: `error on inserting application ERROR #23502 null value in column \"message\" violates not-null constraint`

I am just pointing this out ^ in case you think both controllers should have printed the same error msg.

---

REF: https://issues.redhat.com/browse/GITOPSRVCE-70

### CODE REVIEW

**Comment by jgwest** [comment]
@drpaneas Code looks great, everything looks as expected based on the story description. Thanks for the detailed the description of behaviour and the process you followed to get there. :+1:

## Database field sanitizing

Your mention of magic numbers in the length of database fields got me thinking: we should probably convert those magic numbers to constants in the code, and start making sure we sanitize these fields before storing them in our database.

```go
// Add to somewhere like the 'backend-shared/util' package, so it can be called by the other components.

func TruncateFieldWithEllipses(str string, maxLength) {
    // if string is > maxlength, convert it to:
    //   "string..."
    //   where string is truncated down to maxLength-3 characters
    // else return it as is
    //
    // example:
    // truncateFieldWithEllipses("1234567890", 11) returns "12345890"
    // truncateFieldWithEllipses("1234567890", 8) returns "12345..." 
}
``` 

In `backend-shared`, under `config/db`, create a new Go file called `db_field_constants.go`. Add a constant for the field:
```go
const (
    ApplicationState_Message_Length = 1024
)
```

Finally, in your new [ApplicationState create/update code](https://github.com/redhat-appstudio/managed-gitops/blob/48ccc59d89e9eb5fd82a06f8ee7fc4fc6b59dcfb/cluster-agent/controllers/argoproj.io/application_controller.go#L114), add:
```go
// Ensures that the message we write to the database has max expected number of chars
applicationState.Message = sharedUtilTruncateFieldWithEllipses(app.Status.Health.Message, db.ApplicationState_Message_Length)
```

But, you may be asking, how do we keep constants in `db_field_constants.go` like `ApplicationState_Message_Length` in sync with our actual database schema? 

As part of a separate story (not required for this PR, I'll add details to another story):
- We write a quick Go tool that scans `db_field_constants.go`, and `db_schema.go`, and ensure the values within them are in sync.
- We add that tool to our CI (GitHub action), and have it fail if they are out of sync, to ensure that any changes made to one of those fields must be made to the other.

This lets us at least ensure that the magic numbers we are using are constants, are consistent with the database, and we are using them to sanitize input data.

**Comment by drpaneas** [comment]
> (I also checked the two error messages you mentioned. Based on the context of the code, it seems like the error messages are correct, they are just doing slightly different things. I'll keep an eye on it, potentially one of the messages needs to be updated to be more accurate about what it is doing...)

Yes, it seems we need to wrap errors better to make debugging easier. For example:

```go
// getApplicationFromDB returns the corresponding database entry (Application table row)
// for a given GitOps Deployment UID and a set of Application-scoped DB Queries.
func getApplicationFromDB(ctx context.Context, gitopsDeploymentUID string, dbQueries db.ApplicationScopedQueries) (db.DeploymentToApplicationMapping, error) {

	applicationMapping := db.DeploymentToApplicationMapping{
		Deploymenttoapplicationmapping_uid_id: gitopsDeploymentUID, // UID from the CR's Metadata section
		DeploymentName:                        "",                  // name of the CR
		DeploymentNamespace:                   "",                  // namespace where the CR belongs
		WorkspaceUID:                          "",
		Application_id:                        "", // Argo CD Application identifier
		SeqID:                                 0,
	}

	var wrapErr error
	if err := dbQueries.UncheckedGetDeploymentToApplicationMappingByDeplId(ctx, &applicationMapping); err != nil {
		wrapErr = fmt.Errorf("failed to get the corrersponding database entry (Application table row) for "+
			"the GitOps Deployment CR with UID: '%v' - Error: %w", gitopsDeploymentUID, err)
	}

	return applicationMapping, wrapErr
}
```

> 
> ## Database field sanitizing
> Your mention of magic numbers in the length of database fields got me thinking: we should probably convert those magic numbers to constants in the code, and start making sure we sanitize these fields before storing them in our database.
> 
> ```go
> // Add to somewhere like the 'backend-shared/util' package, so it can be called by the other components.
> 
> func TruncateFieldWithEllipses(str string, maxLength) {
>     // if string is > maxlength, convert it to:
>     //   "string..."
>     //   where string is truncated down to maxLength-3 characters
>     // else return it as is
>     //
>     // example:
>     // truncateFieldWithEllipses("1234567890", 11) returns "12345890"
>     // truncateFieldWithEllipses("1234567890", 8) returns "12345..." 
> }
> ```
> 
> In `backend-shared`, under `config/db`, create a new Go file called `db_field_constants.go`. Add a constant for the field:
> 
> ```go
> const (
>     ApplicationState_Message_Length = 1024
> )
> ```
> 
> Finally, in your new [ApplicationState create/update code](https://github.com/redhat-appstudio/managed-gitops/blob/48ccc59d89e9eb5fd82a06f8ee7fc4fc6b59dcfb/cluster-agent/controllers/argoproj.io/application_controller.go#L114), add:
> 
> ```go
> // Ensures that the message we write to the database has max expected number of chars
> applicationState.Message = sharedUtilTruncateFieldWithEllipses(app.Status.Health.Message, db.ApplicationState_Message_Length)
> ```
> 
> But, you may be asking, how do we keep constants in `db_field_constants.go` like `ApplicationState_Message_Length` in sync with our actual database schema?
> 
> As part of a separate story (not required for this PR, I'll add details to another story):
> 
> * We write a quick Go tool that scans `db_field_constants.go`, and `db_schema.go`, and ensure the values within them are in sync.
> * We add that tool to our CI (GitHub action), and have it fail if they are out of sync, to ensure that any changes made to one of those fields must be made to the other.
> 
> This lets us at least ensure that the magic numbers we are using are constants, are consistent with the database, and we are using them to sanitize input data.

**Comment by drpaneas** [comment]
According to the PostgreSQL docs, the `VARCHAR` is counting characters, not bytes. This is important piece of knowledge, because Go treat string slices as bytes. The encoding in both cases is of course UTF-8.

```shell
$ psql postgresql://postgres:3CqCKcXLyN@127.0.0.1:5432/postgres "-l"
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
(3 rows)
```

I applied the following functional testing:

## Test 1: Find what is the behavior if we write more chars than expected to varchar

Modify db-schema.sql:

```diff
- health VARCHAR (30) NOT NULL,
+ health VARCHAR (5) NOT NULL,
```

Start the k8s devenv and apply a GitopsDeploymentCR.
The default message is [https://github.com/redhat-appstudio/managed-gitops/blob/main/cluster-agent/controllers/argoproj.io/application_controller.go#L148](Unknown) string (7 chars).

Let's see what would be the behavior. Run:

1. Reset your k8s cluster
2. Run: `make devenv-k8s IMG=quay.io/pgeorgia/gitops-service:latest`
3. Local port-forward the db: `kubectl port-forward --namespace gitops svc/gitops-postgresql-staging 5432:5432 &`
4. Start the operators: `DB_PASS=3CqCKcXLyN && goreman start`
5. Apply a new GitOpsDeployment CR: `kubectl apply -f test.yaml`
6. See its YAML: `kubectl -n default get gitopsdeployments gitopsdeployment-sample -o yaml`

Nothing is written in the status field.

See the cluster-agent logs:

cluster-agent:

```json
ERROR controller-runtime.manager.controller.application unexpected error on writing new application state {"reconciler group": "argoproj.io", "reconciler kind": "Application", "name": "gitopsdepl-4833d01d-0984-4990-9e8b-843f5a3c3d7e", "namespace": "argocd", "name": "gitopsdepl-4833d01d-0984-4990-9e8b-843f5a3c3d7e", "namespace": "argocd", "applicationID": "bd389787-b63f-4a9a-a8f4-032a85682181", "error": "error on inserting application ERROR #22001 value too long for type character varying(5)"}
```


See the backend logs:

```json
ApplicationState not found for application, on deploymentStatusTick: bd389787-b63f-4a9a-a8f4-032a85682181 {"gitopsDeplUID": "4833d01d-0984-4990-9e8b-843f5a3c3d7e", "workspaceID": "4eda7ea2-951a-4092-a7b4-3e31129be60d", "debugContext": "deployment"}
```


Result: 
If the string we pass to DB is longer than the VARCHAR, it doesn't get written. The controller errors out and the backend cannot find the applicationState. So it makes sense check if our code is respecting varchar boundaries.


## Test 2: Check if indeed VARCHAR counts chars instead of bytes

Modify db-schema.sql:

```diff
- health VARCHAR (30) NOT NULL,
+ health VARCHAR (5) NOT NULL,
```

Modify the `application_controller.go`:

```diff
- applicationState.Health = "僤凘墈 葎" // 5 chars
+ applicationState.Health = "Unknown"

Start the k8s devenv and apply a GitopsDeploymentCR.
The default message is [https://github.com/redhat-appstudio/managed-gitops/blob/main/cluster-agent/controllers/argoproj.io/application_controller.go#L148](Unknown) string (7 chars).

Let's see what would be the behavior. Run:

1. Reset your k8s cluster
2. Run: `make devenv-k8s IMG=quay.io/pgeorgia/gitops-service:latest`
3. Local port-forward the db: `kubectl port-forward --namespace gitops svc/gitops-postgresql-staging 5432:5432 &`
4. Start the operators: `DB_PASS=3CqCKcXLyN && goreman start`
5. Apply a new GitOpsDeployment CR: `kubectl apply -f test.yaml`
6. See its YAML: `kubectl -n default get gitopsdeployments gitopsdeployment-sample -o yaml`


```yaml
apiVersion: managed-gitops.redhat.com/v1alpha1
kind: GitOpsDeployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"managed-gitops.redhat.com/v1alpha1","kind":"GitOpsDeployment","metadata":{"annotations":{},"name":"gitopsdeployment-sample","namespace":"default"},"spec":{"source":{"repoURL":"https://github.com/drpaneas/whatever"},"type":"manual"}}
  creationTimestamp: "2022-02-17T09:40:27Z"
  generation: 1
  name: gitopsdeployment-sample
  namespace: default
  resourceVersion: "861"
  uid: 042c8c60-bce3-4338-8760-6bbc893bfaab
spec:
  source:
    repoURL: https://github.com/drpaneas/whatever
  type: manual
status:
  health:
    status: 僤凘墈 葎
  sync:
    status: Unknown
```

Result:
As you can see VARCHAR is indeed is counting characters, not bytes. So even a multi-byte char (like the Chinese string) is counted as expected


## Test 3: Make sure the current function sanitizes correctly

Modify db-schema.sql:

```diff
- health VARCHAR (30) NOT NULL,
+ health VARCHAR (5) NOT NULL,
```

Modify the code accordingly:

```go
      applicationState.Health = db.TruncateVarchar("僤凘墈 葎萻萶 僤凘墈 葎萻萶 僤凘墈 葎萻萶", 5)
```

Start the k8s devenv and apply a GitopsDeploymentCR.
The default message is [https://github.com/redhat-appstudio/managed-gitops/blob/main/cluster-agent/controllers/argoproj.io/application_controller.go#L148](Unknown) string (7 chars).

Let's see what would be the behavior. Run:

1. Reset your k8s cluster
2. Run: `make devenv-k8s IMG=quay.io/pgeorgia/gitops-service:latest`
3. Local port-forward the db: `kubectl port-forward --namespace gitops svc/gitops-postgresql-staging 5432:5432 &`
4. Start the operators: `DB_PASS=3CqCKcXLyN && goreman start`
5. Apply a new GitOpsDeployment CR: `kubectl apply -f test.yaml`
6. See its YAML: `kubectl -n default get gitopsdeployments gitopsdeployment-sample -o yaml`


```yaml
apiVersion: managed-gitops.redhat.com/v1alpha1
kind: GitOpsDeployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"managed-gitops.redhat.com/v1alpha1","kind":"GitOpsDeployment","metadata":{"annotations":{},"name":"gitopsdeployment-sample","namespace":"default"},"spec":{"source":{"repoURL":"https://github.com/drpaneas/whatever"},"type":"manual"}}
  creationTimestamp: "2022-02-17T09:51:57Z"
  generation: 1
  name: gitopsdeployment-sample
  namespace: default
  resourceVersion: "913"
  uid: 731937e4-7c6c-4673-9123-c28f5a7722d9
spec:
  source:
    repoURL: https://github.com/drpaneas/whatever
  type: manual
status:
  health:
    status: 僤凘...
  sync:
    status: Unknown
```

Result: 
As you can see the function works correctly, returning 5 multi-byte chars.


---

As you can see the CI is failing because testing is missing. I would need some help on this, as this PR is adding code to the final part of the https://github.com/redhat-appstudio/managed-gitops/blob/11ad94932417a009e7e6a4ab580fe34fdb97f1d2/backend/eventloop/application_event_runner.go#L513

> (I also checked the two error messages you mentioned. Based on the context of the code, it seems like the error messages are correct, they are just doing slightly different things. I'll keep an eye on it, potentially one of the messages needs to be updated to be more accurate about what it is doing...)

Yes, it seems we need to wrap errors better to make debugging easier. For example, if we split the `applicationEventRunner_handleUpdateDeploymentStatus` down to individual parts (see the comments in the function are even suggesting this, counting down steps). e.g. the first part would be something like this:

```go
// getApplicationFromDB returns the corresponding database entry (Application table row)
// for a given GitOps Deployment UID and a set of Application-scoped DB Queries.
func getApplicationFromDB(ctx context.Context, gitopsDeploymentUID string, dbQueries db.ApplicationScopedQueries) (db.DeploymentToApplicationMapping, error) {

	applicationMapping := db.DeploymentToApplicationMapping{
		Deploymenttoapplicationmapping_uid_id: gitopsDeploymentUID, // UID from the CR's Metadata section
		DeploymentName:                        "",                  // name of the CR
		DeploymentNamespace:                   "",                  // namespace where the CR belongs
		WorkspaceUID:                          "",
		Application_id:                        "", // Argo CD Application identifier
		SeqID:                                 0,
	}

	var wrapErr error
	if err := dbQueries.UncheckedGetDeploymentToApplicationMappingByDeplId(ctx, &applicationMapping); err != nil {
		wrapErr = fmt.Errorf("failed to get the corrersponding database entry (Application table row) for "+
			"the GitOps Deployment CR with UID: '%v' - Error: %w", gitopsDeploymentUID, err)
	}

	return applicationMapping, wrapErr
}
```

**Review by jgwest — APPROVED** [review]
Looks great, thanks @drpaneas! Thanks for the detailed investigation of Go and Postgresql varchars, glad to see these are straightforward to work with, and the tests you've added should ensure we are good to go. 

I'll follow up with additional stories for testing (which, as you said, would likely involve other existing work we are doing) and I'm going to open a separate story to setup CI checks to make sure that what is in `db-schema.sql` matches what is in `db_field_constants.go`

**Pull request merged**
