### PR TITLE
Bump Go version from 1.17.6 to 1.18

### PR DESCRIPTION
**Pull request by drpaneas**
#### Description:
- Bumps of the Go version to 1.18.
- Unifies the Go version from GitHub Actions by letting them read the version number from the backend's component `go.mod` file. This will always use the latest minor version (e.g. 1.18.2 as of writing).
- Bumps of the Go version for Dockerfile and OpenShift CI
- Replaces deprecated `go get -u` to `go install`
- Bumps golangci-lint to 1.46.2

>  Note: Go 1.18 is one of the best releases ever and everyone needs to get up to speed with the [new features](https://go.dev/blog/go1.18):
1. Generics (allows you to write functions that accept more than one data type)
2. Fuzzines (allows to write unit-tests where Golang guesses the input for you)
3. Workspaces (a new way to deal with dependencies and modules)
4. 20% performance boost

#### Link to JIRA Story (if applicable):

No JIRA story

### CODE REVIEW

**Review by samyak-jn — APPROVED** [review]
LGTM, the ci being :green_circle: is a good sign indeed.
My only worry is the appstudio-shared module should be consistent with other appstudio components (if needed!)

**Comment by drpaneas** [comment]
Thanks for the review @samyak-jn <3

> the appstudio-shared module should be consistent with other appstudio components (if needed!)

And it is not? :confused: I don't see how the version bump makes the public API inconsistent in that case. The consumers can have a lower Go version if they like. :sunglasses:

**Review by jgwest — APPROVED** [review]
LGTM, thanks @drpaneas!

**Pull request merged**
