### PR TITLE
Move webhooks to GitOps-Service.

### PR DESCRIPTION
**Pull request by jparsai**
## Description
This PR is to move GitOps Service related webhooks to managed-gitops repo from application.
[An application-api PR](https://github.com/redhat-appstudio/application-api/pull/76) was merged which removed GitOps-Service related webhooks from there and in this PR all those webhooks are added with few modifications.

## Jira Ticket
https://issues.redhat.com/browse/GITOPSRVCE-762

### CODE REVIEW

**Comment by jgwest** [comment]
@jparsai I took a quick peek and changes look great! Current E2E tests are probably failing because these lines were removed from the Mutating/Validating webhook:
```
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
```
(see original manifest for an example)

**Comment by jparsai** [comment]
Yes @jgwest make manifest did not include this annotation, added it now.

**Comment by jparsai** [comment]
It is ready for review, PTAL.

**Review by jgwest — APPROVED** [review]
Looks perfect, thanks @jparsai!

**Pull request merged**
