### PR TITLE
Update OpenShift GitOps Subscription channel to gitops-1.10

### PR DESCRIPTION
**Pull request by jgwest**
#### Description:
- Upgrade OpenShift GitOps to GitOps 1.10 channel

### CODE REVIEW

**Review by chetan-rns — APPROVED** [review]
/lgtm

**Comment by chetan-rns** [comment]
@jgwest Argo CD is updated to v2.8.3 in GitOps operator 1.10. Should we also update the Argo CD packages in the same PR?

**Comment by jgwest** [comment]
Thanks @chetan-rns!

**Pull request merged**
