### PR TITLE
Improve SnapshotEnvironmentBinding error reporting APIs

### PR DESCRIPTION
**Pull request by jopit**
#### Description:
- Added a new status condition which will be less subject to misinterpretation.

### CODE REVIEW

**Review by chetan-rns — COMMENTED** [review]
Looks great @jopit . Please rebase your PR and everything else looks good.

**Comment by jgwest** [comment]
@jopit yup, LGTM too, just need to rebase, and I'll skim through one more time, then good to go.

**Review by jgwest — CHANGES_REQUESTED** [review]
Thanks for @jopit  rebasing, everything looks great!  

One more thing I thought of upon re-review: would it be possible to update the E2E tests for this PR as well? I recalled that with the sibling PR there were both [E2E test changes](https://github.com/redhat-appstudio/managed-gitops/pull/516) and unit tests to verify the functionality, it couldn't hurt to do that here as well.

**Review by jgwest — APPROVED** [review]
Looks great, thanks @jopit! I've opened a new story to add E2E tests for SEB.

**Pull request merged**
